# Generated by Django 3.0.8 on 2021-01-18 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IrwinData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.DecimalField(decimal_places=15, max_digits=19)),
                ('lattitude', models.DecimalField(decimal_places=15, max_digits=19)),
                ('irwinid', models.CharField(max_length=50)),
                ('incidentname', models.CharField(max_length=256)),
                ('city', models.CharField(max_length=30)),
                ('county', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=3)),
                ('cdate', models.DateTimeField()),
                ('mdate', models.DateTimeField()),
            ],
        ),
    ]
