# Generated by Django 3.0.8 on 2021-01-18 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firealert', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='irwindata',
            name='city',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
