# Generated by Django 3.0.8 on 2021-01-18 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firealert', '0003_auto_20210118_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='irwindata',
            name='irwinid',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
